language: c
sudo: true

deploy:
  provider: pypi
  user: bgruening
  password:
    secure: AZVacwZdbN+vKXpZm/XjhRrlkJ9LBEn3Xzz7HkOo/yOk6M2rOHpjumsYzIB6YXnJGrR8ZdOJ3nDOwRaqq3LItXLcH05Pf6cajNwGzD3XLKFpqT+M+RYyki+hKjpEZtdKkkxas4FJQ1+x+yQkbYOjyWYz25xJOaAMOmyTmSZio8vK/0k/XJA+yg1uBHUc+xlP7MKygDItXDx0WVEKhbh+I/EqIi2D+SJFtgao/Y25qFzpplmXE5goe6eM4vAFrAzlahadfWggy2N+fx7gkMB5MOzxeUwKYbp7d2qftnSsBO+9P1Bh78g1nBw1MH3a+zqCGeMTmdbU1VdZUXuUsc5aiEL2lVcYOcB499rmssLuS5FALrtVxmEVMRVd/TQD8BOTmZIc7msuoviNt/HChEN6ldkNCHDh1paAnSMsbSmvKmFKr4rXkQNhvKa1D+78MtypPdxgt5cap+WMxGou4+WpzQ2OYfCrcFLWPwIyyBZ4tUr5xXX84AOmyD2OopbFq/1k1wkBvITWexncxxHdFQfCmzO5lDLruWKzr5FyrrBAgZERveqy5PHMp6v8teHfHTVnUMTuB2LZFltBdJL4U+bsOKy0WColpcppBo/kbvSQJY1YgMPuYBRrK1P1r0NkP83kywoAFwC0uMjfBvPcbYGQJHLLRYUYlDDmdao+sbMF6u8=
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  python: 3.6

env:
  - TRAVIS_PYTHON_VERSION=3.6
  - TRAVIS_PYTHON_VERSION=3.7
os:
- linux
- osx

stages:
- lint
- test

before_install:

- export HIC_TEST_DATA_DIR="`pwd`/hicmatrix/test/test_data/"
- echo $HIC_TEST_DATA_DIR
- if [[ "$TRAVIS_OS_NAME" == "linux"]]; then
  curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o miniconda.sh
  ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl
  https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o miniconda.sh
  ; fi
- bash miniconda.sh -b -p $HOME/miniconda
- PATH_WITHOUT_CONDA="$PATH"
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a

install:
- conda install --yes -c conda-forge -c bioconda python=$TRAVIS_PYTHON_VERSION --file
  requirements.txt
- conda install --yes -c conda-forge -c bioconda pytest
- conda install --yes flake8
- python setup.py install

script:
- flake8 . --exclude=.venv,.build,planemo_test_env,build --ignore=E501,F401,F403,E402,F999,F405,E712
- py.test hicmatrix/test/ --capture=sys

