language: c
sudo: true

env:
  - TRAVIS_PYTHON_VERSION=2.7
  - TRAVIS_PYTHON_VERSION=3.6
os:
  - linux
  - osx
stages:
  - lint
  - test

# Setup anaconda
before_install:
  - export HIC_TEST_DATA_DIR="`pwd`/hicexplorer/test/test_data/"
  - echo $HIC_TEST_DATA_DIR
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then curl https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -o miniconda.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o miniconda.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then curl https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -o miniconda.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o miniconda.sh ; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - PATH_WITHOUT_CONDA="$PATH"
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
# Install packages
install:
  - conda install --yes -c conda-forge -c bioconda python=$TRAVIS_PYTHON_VERSION --file requirements.txt
  - conda install --yes -c conda-forge -c bioconda pytest
  - conda install --yes flake8
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then conda install --yes -c defaults -c conda-forge -c bioconda configparser ; fi
  - python setup.py install
# command to run tests
script:
  - flake8 . --exclude=.venv,.build,planemo_test_env,build --ignore=E501,F401,F403,E402,F999,F405,E712
  - py.test hicexplorer/test/ --doctest-modules --capture=sys
  - py.test hicexplorer --doctest-modules --ignore=hicexplorer/test/
